image: node:20

stages:
  - .pre
  - build
  - deploy

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - node_modules/
    - .pnpm-store/

default:
  tags:
    - public-runner-docker

.pnpm_based_job:
  before_script:
    - corepack enable
    - corepack prepare pnpm@9.1.1 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install

lint:
  stage: .pre
  extends: .pnpm_based_job
  script:
    - pnpm run lint
  rules:
    - when: always

build:
  stage: build
  extends: .pnpm_based_job
  needs:
    - job: lint
  script:
    # Replace the base URL in retype.yml with the GitLab Pages URL
    - sed -i "s#http://localhost:5005#$CI_PAGES_URL#g" retype.yml
    - pnpm run build
  artifacts:
    paths:
      - ".retype"
    when: always
    expire_in: 1 week
  only:
    - main

build_preview:
  stage: build
  extends: .pnpm_based_job
  needs:
    - job: lint
  variables:
    PREVIEW_URL: "$CI_PAGES_URL/-/mr-$CI_MERGE_REQUEST_IID"
  script:
    # Replace the base URL in retype.yml with the GitLab Pages URL
    - sed -i "s#http://localhost:5005#$PREVIEW_URL#g" retype.yml
    - pnpm run build
  artifacts:
    paths:
      - ".retype"
    when: always
    expire_in: 1 week
  only:
    - merge_requests

pages:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
    - mkdir -p public
    - cp -r .retype/* public
    - echo "Documentation preview deployed to $PREVIEW_URL"
  publish: public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main

preview:
  stage: deploy
  needs:
    - job: build_preview
      artifacts: true
  variables:
    PREVIEW_URL: "$CI_PAGES_URL/-/mr-$CI_MERGE_REQUEST_IID"
  script:
    # Create the preview directory structure
    - mkdir -p public/-/mr-$CI_MERGE_REQUEST_IID
    - cp -r .retype/* public/-/mr-$CI_MERGE_REQUEST_IID/
    - echo "Documentation preview deployed to $PREVIEW_URL"
  artifacts:
    paths:
      - public
    expire_in: 1 week
  environment:
    name: wax-doc/-/mr-$CI_MERGE_REQUEST_IID
    url: "$PREVIEW_URL"
    on_stop: cleanup_preview
  only:
    - merge_requests

cleanup_preview:
  stage: deploy
  script:
    - echo "Cleaning up preview environment for MR $CI_MERGE_REQUEST_IID"
    - rm -rf public/-/mr-$CI_MERGE_REQUEST_IID
  environment:
    name: wax-doc/-/mr-$CI_MERGE_REQUEST_IID
    action: stop
  when: manual
  only:
    - merge_requests
